Alias /who-update-demo-media/ /srv/maksonchik/demo_media/

<Directory /srv/maksonchik/demo_media>
    Options -Indexes
    Require all granted
    <FilesMatch "\.mp4$">
        Header set Cache-Control "public, max-age=604800"
    </FilesMatch>
</Directory>
