server {
    server_name maksonchik.ru www.maksonchik.ru;

    location = /favicon.ico {
        alias /root/maksonchik/favicon.ico;
        access_log off;
        log_not_found off;
    }

    location /static/ {
        root /root/maksonchik;
    }

    location / {
        set $frame_options "";
        if ($http_referer !~* "^https?://([^/]+\\.)?(maksonchik\\.ru|webvisor\\.com|metri[ck]a\\.yandex\\.(com|ru|by|com\\.tr))/") {
            set $frame_options "SAMEORIGIN";
        }

        include proxy_params;
        proxy_hide_header X-Frame-Options;
        add_header X-Frame-Options $frame_options always;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/maksonchik.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/maksonchik.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.maksonchik.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = maksonchik.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name maksonchik.ru www.maksonchik.ru;
    return 404; # managed by Certbot
}
