# Generated by Django 6.0.2 on 2026-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.AddField(
            model_name='message',
            name='username_from',
            field=models.TextField(default='', verbose_name='Username sender'),
        ),
        migrations.AddField(
            model_name='usertg',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='Не текстовое сообщение', verbose_name='Text'),
        ),
    ]
