# Generated by Django 6.0.2 on 2026-02-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0003_alter_message_options_alter_usertg_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='username_from',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Username sender'),
        ),
    ]
