# Generated by Django 6.0.2 on 2026-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0004_alter_message_username_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chat id'),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='message',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='First name sender'),
        ),
        migrations.AddField(
            model_name='usertg',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='First name sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username_from',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Username sender'),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Username'),
        ),
    ]
