# Generated by Django 6.0.2 on 2026-02-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0005_message_chat_id_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='business_connection_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Business connection id'),
        ),
    ]
