# Generated by Django 6.0.2 on 2026-03-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0007_adminchatfilter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchatfilter',
            name='chat_id',
            field=models.BigIntegerField(help_text='Пользователь видит сообщения с этим chat_id', verbose_name='Chat id'),
        ),
        migrations.AlterField(
            model_name='adminchatfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_filters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='adminchatfilter',
            unique_together={('user', 'chat_id')},
        ),
    ]
