# Generated by Django 6.0.2 on 2026-03-03 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0008_alter_adminchatfilter_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminchatfilter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adminchatfilter',
            name='business_connection_id',
            field=models.CharField(blank=True, help_text='Если указан — доступ только к сообщениям с этим business_connection_id и chat_id. Пусто — все сообщения этого chat_id.', max_length=255, null=True, verbose_name='Business connection id'),
        ),
        migrations.AlterField(
            model_name='adminchatfilter',
            name='chat_id',
            field=models.BigIntegerField(help_text='Chat id из Telegram', verbose_name='Chat id'),
        ),
        migrations.AlterUniqueTogether(
            name='adminchatfilter',
            unique_together={('user', 'chat_id', 'business_connection_id')},
        ),
    ]
