# Generated by Django 6.0.2 on 2026-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0009_alter_adminchatfilter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Текст к файлу'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File id'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Неизвестно'), ('PHOTO', 'Фото'), ('AUDIO', 'Аудио'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ')], default='UNKNOWN', max_length=20, null=True, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='message',
            name='payload',
            field=models.TextField(blank=True, default='', null=True, verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
