# Generated by Django 6.1.1 on 2026-09-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_tg', '0034_video_note_with_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramoutbox',
            name='method',
            field=models.CharField(choices=[('sendMessage', 'sendMessage'), ('sendPhoto', 'sendPhoto'), ('sendAudio', 'sendAudio'), ('sendVideo', 'sendVideo'), ('sendVideoNoteWithText', 'Кружок, затем текст'), ('sendMediaWithText', 'Медиа, затем текст'), ('sendDocument', 'sendDocument'), ('sendDocumentBytes', 'sendDocumentBytes')], max_length=32, verbose_name='Метод Telegram API'),
        ),
    ]
